version: "3.4"

services:
  api:
    image: phpswoole/swoole
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: api
    working_dir: /opt/app
    network_mode: host
    # restart: always
    volumes:
      - $PWD:/opt/app
    command: php artisan swoole:http start
    expose:
      - "8080"
